version: '3'
services:
  php-apache:
    container_name: php-apache
    image: tomsik68/xampp:7
    volumes:
      - ./php:/www
    ports:
      - 8000:80
  db:
    image: mysql:5.7.40
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: db_test